"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Navigation } from "@/components/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { GenerateRecapResponse } from "@/lib/types";
import { generateRecap } from "@/lib/api";
import { 
  Sparkles, Copy, Loader2, 
  CheckCircle2, XCircle, Lightbulb, Trophy 
} from "lucide-react";
import {
  fadeInUp,
  fadeInDown,
  staggerContainer,
  staggerItem,
  scaleFadeIn,
  buttonHover,
  pulse,
  float
} from "@/lib/animations";

export default function RecapPage() {
  const router = useRouter();
  const [recap, setRecap] = useState<GenerateRecapResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [playerInfo, setPlayerInfo] = useState<{ gameName: string; tagLine: string } | null>(null);
  const recapCardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const info = sessionStorage.getItem("playerInfo");
    if (!info) {
      router.push("/");
      return;
    }
    setPlayerInfo(JSON.parse(info));
  }, [router]);

  const handleGenerateRecap = async () => {
    if (!playerInfo) return;

    setIsLoading(true);
    try {
      toast.info("Generating your AI recap...");
      const data = await generateRecap(playerInfo.gameName, playerInfo.tagLine, "americas");
      setRecap(data);
      toast.success("Recap generated! 🎉");
    } catch (error) {
      console.error("Error:", error);
      toast.error(error instanceof Error ? error.message : "Failed to generate recap");
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = () => {
    if (!recap) return;

    const text = `
🎮 ${playerInfo?.gameName}#${playerInfo?.tagLine} - Season Recap

🎭 PERSONALITY: ${recap.recap.personality_profile}

✨ PLAYSTYLE: ${recap.recap.playstyle_summary}

💪 STRENGTHS:
${recap.recap.strengths.map(s => `• ${s}`).join('\n')}

⚠️ WEAKNESSES:
${recap.recap.weaknesses.map(w => `• ${w}`).join('\n')}

💡 TIP: ${recap.recap.actionable_tip}

🌟 HIGHLIGHT: ${recap.recap.fun_highlight}

📊 STATS: ${recap.stats_summary.total_matches} games • ${recap.stats_summary.win_rate} winrate • ${recap.stats_summary.most_played_champion} main

Generated by Rift Rewind
    `.trim();

    navigator.clipboard.writeText(text);
    toast.success("Copied to clipboard!");
  };

  if (!playerInfo) {
    return (
      <>
        <Navigation />
        <div className="container mx-auto px-4 py-20 text-center">
          <p className="text-slate-400">Loading...</p>
        </div>
      </>
    );
  }

  return (
    <>
      <Navigation />
      
      <main className="container mx-auto px-4 py-8 space-y-8">
        {/* Header */}
        <motion.div 
          className="text-center space-y-4"
          initial="initial"
          animate="animate"
          variants={staggerContainer}
        >
          <motion.h1 
            className="text-5xl font-bold bg-gradient-to-r from-pink-400 via-purple-500 to-indigo-500 bg-clip-text text-transparent"
            variants={fadeInDown}
          >
            Your Season Recap
          </motion.h1>
          <motion.p 
            className="text-slate-400"
            variants={fadeInUp}
          >
            {playerInfo.gameName}#{playerInfo.tagLine}
          </motion.p>
          
          {!recap && (
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3 }}
            >
              <motion.div {...buttonHover}>
                <Button
                  onClick={handleGenerateRecap}
                  disabled={isLoading}
                  size="lg"
                  className="mt-4 bg-gradient-to-r from-pink-500 to-purple-500 hover:from-pink-600 hover:to-purple-600"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                      Generating Magic...
                    </>
                  ) : (
                    <>
                      <motion.div {...pulse}>
                        <Sparkles className="mr-2 h-5 w-5" />
                      </motion.div>
                      Generate AI Recap
                    </>
                  )}
                </Button>
              </motion.div>
            </motion.div>
          )}
        </motion.div>

        {/* Recap Card */}
        {recap && (
          <motion.div 
            className="space-y-6"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
          >
            {/* Action Buttons */}
            <motion.div 
              className="flex justify-center gap-4"
              initial="initial"
              animate="animate"
              variants={staggerContainer}
            >
              <motion.div variants={staggerItem} {...buttonHover}>
                <Button
                  onClick={handleCopy}
                  variant="outline"
                  className="border-slate-700"
                >
                  <Copy className="mr-2 h-4 w-4" />
                  Copy Summary
                </Button>
              </motion.div>
            </motion.div>

            {/* Recap Content */}
            <motion.div 
              ref={recapCardRef}
              className="max-w-4xl mx-auto space-y-6 p-8 bg-gradient-to-br from-slate-900/90 via-purple-900/20 to-slate-900/90 border border-purple-500/30 rounded-2xl backdrop-blur-xl"
              initial="initial"
              animate="animate"
              variants={staggerContainer}
            >
              {/* Player Info */}
              <div className="text-center space-y-2 pb-6 border-b border-slate-700/50">
                <h2 className="text-4xl font-bold text-transparent bg-gradient-to-r from-yellow-400 to-pink-500 bg-clip-text">
                  {playerInfo.gameName}#{playerInfo.tagLine}
                </h2>
                <p className="text-slate-400">Season Wrapped</p>
                <p className="text-sm text-slate-500">
                  {recap.stats_summary.total_matches} games • {recap.stats_summary.win_rate} WR • {recap.stats_summary.most_played_champion}
                </p>
              </div>

              {/* Personality Profile */}
              <Card className="bg-slate-800/50 border-pink-500/30 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-pink-400">
                    <Trophy className="h-5 w-5" />
                    Your Personality
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-lg text-slate-200 leading-relaxed">
                    {recap.recap.personality_profile}
                  </p>
                </CardContent>
              </Card>

              {/* Playstyle Summary */}
              <Card className="bg-slate-800/50 border-purple-500/30 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-purple-400">
                    <Sparkles className="h-5 w-5" />
                    Your Playstyle
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-lg text-slate-200 leading-relaxed">
                    {recap.recap.playstyle_summary}
                  </p>
                </CardContent>
              </Card>

              {/* Strengths & Weaknesses */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Strengths */}
                <Card className="bg-slate-800/50 border-green-500/30 backdrop-blur-sm">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-green-400">
                      <CheckCircle2 className="h-5 w-5" />
                      Strengths
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {recap.recap.strengths.map((strength, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <Badge variant="outline" className="mt-0.5 bg-green-500/10 text-green-400 border-green-500/30">
                            {index + 1}
                          </Badge>
                          <span className="text-slate-200">{strength}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>

                {/* Weaknesses */}
                <Card className="bg-slate-800/50 border-orange-500/30 backdrop-blur-sm">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2 text-orange-400">
                      <XCircle className="h-5 w-5" />
                      Areas to Improve
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {recap.recap.weaknesses.map((weakness, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <Badge variant="outline" className="mt-0.5 bg-orange-500/10 text-orange-400 border-orange-500/30">
                            {index + 1}
                          </Badge>
                          <span className="text-slate-200">{weakness}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              </div>

              {/* Actionable Tip */}
              <Card className="bg-gradient-to-r from-blue-900/30 to-cyan-900/30 border-cyan-500/30 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-cyan-400">
                    <Lightbulb className="h-5 w-5" />
                    Pro Tip
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-lg text-slate-200 leading-relaxed font-medium">
                    💡 {recap.recap.actionable_tip}
                  </p>
                </CardContent>
              </Card>

              {/* Fun Highlight */}
              <Card className="bg-gradient-to-r from-yellow-900/30 to-orange-900/30 border-yellow-500/30 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-yellow-400">
                    <Sparkles className="h-5 w-5" />
                    Fun Highlight
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-lg text-slate-200 leading-relaxed">
                    🌟 {recap.recap.fun_highlight}
                  </p>
                </CardContent>
              </Card>

              {/* Footer */}
              <div className="text-center pt-6 border-t border-slate-700/50">
                <p className="text-sm text-slate-400">
                  Generated by <span className="text-yellow-400 font-semibold">Rift Rewind</span>
                </p>
                <p className="text-xs text-slate-500 mt-1">
                  Your Season, Your Story
                </p>
              </div>
            </motion.div>
          </motion.div>
        )}

        {/* Empty State */}
        {!recap && !isLoading && (
          <motion.div 
            className="text-center py-20 space-y-4"
            initial="initial"
            animate="animate"
            variants={staggerContainer}
          >
            <motion.div {...float}>
              <Sparkles className="h-16 w-16 mx-auto text-purple-400 opacity-50" />
            </motion.div>
            <motion.p 
              className="text-slate-400"
              variants={fadeInUp}
            >
              Click the button above to generate your personalized AI recap
            </motion.p>
          </motion.div>
        )}
      </main>
    </>
  );
}
